"""ProcessedDocument dataclass for representing extracted document data."""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional


@dataclass
class ProcessedDocument:
    """Represents a document processed by Docling with extracted text.

    This dataclass encapsulates all information about a processed image,
    including the extracted text, quality metrics, and optional summary.

    Attributes:
        filename: Just the filename (e.g., "IMG_1210.JPEG")
        file_path: Full absolute path to the source file
        extracted_text: The markdown-formatted text extracted from the image
        extraction_time: Timestamp when the extraction was performed
        success: Whether extraction was successful
        error_message: Error message if extraction failed (None if successful)
        quality_grade: Overall quality grade (EXCELLENT/GOOD/FAIR/POOR)
        quality_score: Overall quality score (0.0-1.0, higher is better)
        low_quality_grade: Conservative quality grade (worst-performing areas)
        low_score: Conservative quality score (5th percentile)
        ocr_score: OCR extraction quality score (0.0-1.0)
        layout_score: Layout detection quality score (0.0-1.0)
        summary: 1-2 sentence summary generated by SmolLM3 (None if not generated)
    """

    filename: str
    file_path: str
    extracted_text: str
    extraction_time: datetime = field(default_factory=datetime.now)
    success: bool = True
    error_message: Optional[str] = None

    # Quality metrics from Docling confidence scores
    quality_grade: Optional[str] = None  # "EXCELLENT", "GOOD", "FAIR", "POOR"
    quality_score: Optional[float] = None  # 0.0-1.0 (mean_score)
    low_quality_grade: Optional[str] = None  # Conservative quality estimate
    low_score: Optional[float] = None  # 5th percentile score
    ocr_score: Optional[float] = None  # OCR quality (0.0-1.0)
    layout_score: Optional[float] = None  # Layout detection quality (0.0-1.0)

    # Title extracted from the first line of markdown
    title: Optional[str] = None  # Poster title (from first heading)

    # Summary from SmolLM3
    summary: Optional[str] = None  # 1-2 sentence summary of the content

    # Processing timing
    processing_time: Optional[float] = None  # Seconds to process this document

    @classmethod
    def from_path(
        cls,
        file_path: str,
        extracted_text: str,
        success: bool = True,
        error_message: Optional[str] = None,
        quality_grade: Optional[str] = None,
        quality_score: Optional[float] = None,
        low_quality_grade: Optional[str] = None,
        low_score: Optional[float] = None,
        ocr_score: Optional[float] = None,
        layout_score: Optional[float] = None,
        title: Optional[str] = None,
        processing_time: Optional[float] = None,
    ) -> "ProcessedDocument":
        """Factory method to create ProcessedDocument from file path.

        Args:
            file_path: Path to the source image file
            extracted_text: The extracted text content
            success: Whether extraction succeeded (default: True)
            error_message: Error message if failed (default: None)
            quality_grade: Overall quality grade from Docling (default: None)
            quality_score: Overall quality score 0.0-1.0 (default: None)
            low_quality_grade: Conservative quality grade (default: None)
            low_score: Conservative quality score (default: None)
            ocr_score: OCR quality score 0.0-1.0 (default: None)
            layout_score: Layout detection quality score 0.0-1.0 (default: None)
            title: Poster title extracted from markdown (default: None)
            processing_time: Seconds to process this document (default: None)

        Returns:
            ProcessedDocument instance
        """
        path = Path(file_path)
        return cls(
            filename=path.name,
            file_path=str(path.absolute()),
            extracted_text=extracted_text,
            success=success,
            error_message=error_message,
            quality_grade=quality_grade,
            quality_score=quality_score,
            low_quality_grade=low_quality_grade,
            low_score=low_score,
            ocr_score=ocr_score,
            layout_score=layout_score,
            title=title,
            processing_time=processing_time,
        )

    @classmethod
    def from_error(
        cls,
        file_path: str,
        error_message: str,
        processing_time: Optional[float] = None,
    ) -> "ProcessedDocument":
        """Factory method to create ProcessedDocument for failed extraction.

        Args:
            file_path: Path to the source image file that failed
            error_message: Description of the error that occurred
            processing_time: Seconds spent before failure (default: None)

        Returns:
            ProcessedDocument instance with success=False
        """
        return cls.from_path(
            file_path=file_path,
            extracted_text="",
            success=False,
            error_message=error_message,
            processing_time=processing_time,
        )
